Clip semantic search
rewardStyle/fairywren pull request #1
Opened 2023-03-23 15:38 UTC by sugi-chan

Creating initial class to handle searching with CLIP + Faiss.  Hopefully this helps with dataset building type things.

Pull Request Checklist
 - [ ] Pull request includes a description of why we are doing this
 - [ ] `CHANGELOG.md` has been updated
 - [ ] Version in `_version.py` has been updated
 - [ ] All tests in the `tests` folder pass with a local build
 - [ ] `requirements.txt` and `requirements-dev.txt` have been recompiled (if applicable)
 - [ ] `__init__.py` file(s) import new capabilities to appropriate level of package (if applicable)
 - [ ] `README.md` has been updated (if applicable)

2023-03-23 17:52 UTC, sugi-chan commented on README.md
> +cd into dir. install as editable library
i should have actual instructions for a lot of the readme.... but I will probably make it another ticket/PR since I need to make and add the logo as well and such

2023-03-24 20:26 UTC, emmafgrimes requested changes
This is awesome @sugi-chan ! great work on this. I added a bunch of nitpicky, optional, and typo comments, but the code itself looks great!

2023-03-24 20:26 UTC, emmafgrimes commented on fairywren/clip/faiss_index_search.py
> +        ----------
Should we include `max_length` here?

2023-03-24 20:26 UTC, emmafgrimes commented on fairywren/clip/faiss_index_search.py
> +        `image_embeds` and `text_embeds` fields in the CLIP output. Fairywern is focused on
Typo
```suggestion
        `image_embeds` and `text_embeds` fields in the CLIP output. Fairywren is focused on
```

2023-03-24 20:26 UTC, emmafgrimes commented on fairywren/clip/faiss_index_search.py
> +                keys and values.
[nitpicky] can we fix the indentation here and below?

2023-03-24 20:26 UTC, emmafgrimes commented on fairywren/clip/faiss_index_search.py
> +        Takes and embedding or array of embeddings, searches the built Faiss index, adds metadata,
Typo
```suggestion
        Takes an embedding or array of embeddings, searches the built Faiss index, adds metadata,
```

2023-03-24 20:26 UTC, emmafgrimes commented on fairywren/clip/faiss_index_search.py
> +                I: the index numbers of results from the faiss index search.
[nitpicky] can we fix the indentation here?

2023-03-24 20:26 UTC, emmafgrimes commented on fairywren/clip/faiss_index_search.py
> +                I: the index numbers of results from the faiss index search.
Should this be `indexes`?

2023-03-24 20:26 UTC, emmafgrimes commented on fairywren/clip/faiss_index_search.py
> +        ```
Should we add a parameters section to this docstring?

2023-03-24 20:26 UTC, emmafgrimes commented on tests/fixtures/data_fixtures.py
> +
Can we remove this line break to be consistent with above? Same for L26 below

2023-03-24 20:26 UTC, emmafgrimes commented on tests/fixtures/data_fixtures.py
> +                                )
[totally optional] mostly curious, would this work?
```suggestion
def fairywren_clip_index(test_embeddings, test_metadata):
    wren_index = CLIPFaissIndex(embedding_array=test_embeddings,
                                id_metadata=test_metadata
                                )
```

2023-03-24 20:26 UTC, emmafgrimes commented on tests/fixtures/data_fixtures.py
> +# unsure if this will run correctly on git TBD
lol did it work?

2023-03-24 20:26 UTC, emmafgrimes commented on tests/test_clip_index.py
> +    print(str(e.value))
Do we need this print statement?

2023-03-24 20:26 UTC, emmafgrimes commented on tests/test_clip_index.py
[totally optional] I like naming my test files based on my function files, so this would be `test_faiss_index_search.py` and the fixture file would be `faiss_index_search_fixtures.py`. This is a personal opinion and I do not feel strongly, just wanted to share.

2023-03-27 15:31 UTC, sugi-chan commented on fairywren/clip/faiss_index_search.py
> +base_processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")
im actually a monster

2023-03-27 15:34 UTC, sugi-chan commented on tests/fixtures/data_fixtures.py
> +# unsure if this will run correctly on git TBD
surprisingly yes, i forget what case is where it doesnt actually work... we did something different in octopod but I forget why

2023-03-27 15:34 UTC, sugi-chan commented on tests/test_clip_index.py
> +    print(str(e.value))
lol no. This was for me when I was crying about tests failing

2023-03-27 15:36 UTC, sugi-chan commented on tests/fixtures/data_fixtures.py
> +                                )
yeah I think that technically would have worrrkeeeddddddd????

2023-03-27 15:40 UTC, sugi-chan commented on fairywren/clip/__init__.py
> +from fairywren.clip.faiss_index_search import CLIPFaissIndex
classic

2023-03-27 16:10 UTC, emmafgrimes commented on fairywren/clip/faiss_index_search.py
> +        is calculated bas on the length of the first element of `self.embedding_array`
same!

2023-03-27 16:13 UTC, sugi-chan commented on fairywren/clip/faiss_index_search.py
> +                keys and values.
things my brain didnt even register while looking through the code... gogo reviews

2023-03-27 17:15 UTC, sugi-chan commented on setup.py
> +    name='fairywren',
yeah I figured it was something of that sort. I did check ahead of time and fairywren is available on pypi haha. i guess it could be problematic if it gets taken by something. unsure

2023-03-27 17:21 UTC, sugi-chan commented on setup.py
> +    name='fairywren',
so fairywren is a potential candidate for open sourcing depending on how we continue to expand it. i dont have real preferences around this

2023-03-28 16:05 UTC, emmafgrimes commented on setup.py
> +    name='fairywren',
makes sense to leave as is!  just wanted to call out why we added the `ltk_` in `beaver`.

2023-03-28 16:12 UTC, emmafgrimes approved these changes
Amazing! Thanks for making all the little changes, this is very exciting!

2023-03-28 16:12 UTC, emmafgrimes commented on fairywren/clip/faiss_index_search.py
> +                indexes: the index numbers of results from the faiss index search.
one last funky indent ;)

2023-03-28 17:37 UTC, emmafgrimes approved these changes
Not sure if you were waiting on me for this 🚢

2023-03-28 19:15 UTC, merged